### ISSUE TITLE
pyrsistent requires Python '>=3.5' but the running Python is 2.7.17

### ISSUE THREAD

**Issue by andrestoga** [boschresearch/pcg_gazebo#123]
Hi,

I'm getting this error while trying to install pcg_gazebo using pip:

"pyrsistent requires Python '>=3.5' but the running Python is 2.7.17"

Best,

**Comment by awesomebytes** [comment]
I ran into this error in a different piece of software (nbformat) days ago. pyrsistent is deprecating python2.7 support.
The trick is to install the latest py2.7 supported version with
```bash
pip install pyrsistent==0.16.1
```

**Comment by andrestoga** [comment]
I didn't work for me... What worked for me was to install it with pip3.

**Comment by andrestoga** [comment]
Thanks! with that fix works but it is not updated in pip.
